# Site settings
title: "Abel Binoop"
email: 
description: "I'm a 13-year-old tech maniac who's also into ornithology and reading. The power of open source software is my jam."
baseurl: ""
url: "programmabel.github.io"
title_description: "I'm a 13-year-old tech maniac who's also into ornithology and reading. The power of open source software is my jam."
title_image: "https://secure.gravatar.com/avatar/f1619ab95f71c45839d2e226e41bc292?s=500"
google_analytics: 
disqus_account: 
github_repository: https://github.com/ProgrammAbel/programmabel.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: ProgrammAbel
instagram_username: 
reddit_username: ProgrammAbel
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_right: "&lt;/&gt; on <a href=\"https://github.com/ProgrammAbel/programmabel.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
